/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author phdam
 */
public class PedidoVenda extends javax.swing.JFrame {

    /**
     * Creates new form PedidoVenda
     */
    public PedidoVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscaCliente2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtConsultaCpf2 = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txtBuscaNome2 = new javax.swing.JTextField();
        bDeletarCliente2 = new javax.swing.JButton();
        bAtualizarCliente2 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        txtBuscaNasc2 = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        bLimparBusca2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ConsultaProdutos2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtConsultaProduto7 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        bLimparConsultar7 = new javax.swing.JButton();
        bBuscar8 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTProdutos8 = new javax.swing.JTable();
        CarrinhoDeCompras = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTProdutos7 = new javax.swing.JTable();
        totalVenda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txTotalVenda = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BuscaCliente2.setBackground(new java.awt.Color(255, 255, 255));
        BuscaCliente2.setBorder(javax.swing.BorderFactory.createTitledBorder("Busca de Clientes"));
        BuscaCliente2.setForeground(new java.awt.Color(153, 255, 153));

        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("CPF");

        try {
            txtConsultaCpf2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Nome");

        txtBuscaNome2.setOpaque(false);

        bDeletarCliente2.setBackground(new java.awt.Color(102, 102, 102));
        bDeletarCliente2.setForeground(new java.awt.Color(153, 255, 153));
        bDeletarCliente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete.png"))); // NOI18N
        bDeletarCliente2.setText("Deletar");
        bDeletarCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeletarCliente2ActionPerformed(evt);
            }
        });

        bAtualizarCliente2.setBackground(new java.awt.Color(102, 102, 102));
        bAtualizarCliente2.setForeground(new java.awt.Color(153, 255, 153));
        bAtualizarCliente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/updated.png"))); // NOI18N
        bAtualizarCliente2.setText("Atualizar");
        bAtualizarCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtualizarCliente2ActionPerformed(evt);
            }
        });

        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Data de Nascimento");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscaNome2)
                    .addComponent(txtBuscaNasc2)
                    .addComponent(bAtualizarCliente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel29))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(bDeletarCliente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscaNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscaNasc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bAtualizarCliente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bDeletarCliente2)
                .addContainerGap())
        );

        bBuscar.setBackground(new java.awt.Color(102, 102, 102));
        bBuscar.setForeground(new java.awt.Color(153, 255, 153));
        bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/binoculars.png"))); // NOI18N
        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bLimparBusca2.setBackground(new java.awt.Color(102, 102, 102));
        bLimparBusca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/limpar-limpo.png"))); // NOI18N
        bLimparBusca2.setText("Limpar");
        bLimparBusca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparBusca2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuscaCliente2Layout = new javax.swing.GroupLayout(BuscaCliente2);
        BuscaCliente2.setLayout(BuscaCliente2Layout);
        BuscaCliente2Layout.setHorizontalGroup(
            BuscaCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaCliente2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscaCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuscaCliente2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(BuscaCliente2Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConsultaCpf2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bLimparBusca2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        BuscaCliente2Layout.setVerticalGroup(
            BuscaCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaCliente2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscaCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtConsultaCpf2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bLimparBusca2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        ConsultaProdutos2.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaProdutos2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Produtos"));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Produto:");

        bLimparConsultar7.setBackground(new java.awt.Color(102, 102, 102));
        bLimparConsultar7.setForeground(new java.awt.Color(153, 255, 153));
        bLimparConsultar7.setText("LIMPAR");
        bLimparConsultar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparConsultar7ActionPerformed(evt);
            }
        });

        bBuscar8.setBackground(new java.awt.Color(102, 102, 102));
        bBuscar8.setForeground(new java.awt.Color(153, 255, 153));
        bBuscar8.setText("BUSCAR");
        bBuscar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscar8ActionPerformed(evt);
            }
        });

        jTProdutos8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Descrição", "Custo", "Venda", "Tamanho", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(jTProdutos8);

        javax.swing.GroupLayout ConsultaProdutos2Layout = new javax.swing.GroupLayout(ConsultaProdutos2);
        ConsultaProdutos2.setLayout(ConsultaProdutos2Layout);
        ConsultaProdutos2Layout.setHorizontalGroup(
            ConsultaProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaProdutos2Layout.createSequentialGroup()
                .addGroup(ConsultaProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultaProdutos2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConsultaProduto7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(bLimparConsultar7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bBuscar8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ConsultaProdutos2Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
        );
        ConsultaProdutos2Layout.setVerticalGroup(
            ConsultaProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaProdutos2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultaProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtConsultaProduto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLimparConsultar7)
                    .addComponent(bBuscar8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConsultaProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultaProdutos2Layout.createSequentialGroup()
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(227, Short.MAX_VALUE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        CarrinhoDeCompras.setBackground(new java.awt.Color(255, 255, 255));
        CarrinhoDeCompras.setBorder(javax.swing.BorderFactory.createTitledBorder("Carrinho de Compras"));

        jTProdutos7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Descrição", "Quantidade", "Preço", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTProdutos7);

        javax.swing.GroupLayout CarrinhoDeComprasLayout = new javax.swing.GroupLayout(CarrinhoDeCompras);
        CarrinhoDeCompras.setLayout(CarrinhoDeComprasLayout);
        CarrinhoDeComprasLayout.setHorizontalGroup(
            CarrinhoDeComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarrinhoDeComprasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
        );
        CarrinhoDeComprasLayout.setVerticalGroup(
            CarrinhoDeComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarrinhoDeComprasLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CarrinhoDeComprasLayout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        totalVenda.setBackground(new java.awt.Color(255, 255, 255));
        totalVenda.setBorder(javax.swing.BorderFactory.createTitledBorder("Total de Venda"));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Total da Venda:");

        txTotalVenda.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txTotalVenda.setForeground(new java.awt.Color(204, 0, 0));
        txTotalVenda.setText("R$");
        txTotalVenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout totalVendaLayout = new javax.swing.GroupLayout(totalVenda);
        totalVenda.setLayout(totalVendaLayout);
        totalVendaLayout.setHorizontalGroup(
            totalVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        totalVendaLayout.setVerticalGroup(
            totalVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalVendaLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(totalVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jMenu1.setText("Opção");

        jMenuItem1.setText("Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ConsultaProdutos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuscaCliente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CarrinhoDeCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BuscaCliente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CarrinhoDeCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ConsultaProdutos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");
        jPanel1.getAccessibleContext().setAccessibleDescription("");
        CarrinhoDeCompras.getAccessibleContext().setAccessibleName("Carrinho de Compras");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void bDeletarCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeletarCliente2ActionPerformed
        CadastroCliente c = new CadastroCliente();
        DAO dao = new DAO();

        dao.deleteCliente(c, txtConsultaCpf2.getText());

        txtConsultaCpf2.setText("");
        txtBuscaNome2.setText("");
        txtBuscaNasc2.setText("");
        txtBuscaTelefone.setText("");
        txtBuscaSexo.setText("");
        txtBuscaCep.setText("");
        txtBuscaEndereco.setText("");
        txtBuscaCidade.setText("");
        txtBuscaEstado.setText("");
    }//GEN-LAST:event_bDeletarCliente2ActionPerformed

    private void bAtualizarCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtualizarCliente2ActionPerformed
        CadastroCliente c = new CadastroCliente();
        DAO dao = new DAO();

        c.setNomeCompleto(txtBuscaNome2.getText());
        c.setDataNascimento(txtBuscaNasc2.getText());
        c.setSexo((String)txtBuscaSexo.getText());
        c.setTelefone(txtBuscaTelefone.getText());
        c.setCep(txtBuscaCep.getText());
        c.setEndereco(txtBuscaEndereco.getText());
        c.setCidade(txtBuscaCidade.getText());
        c.setEstado((String)txtBuscaEstado.getText());
        dao.updateCliente(c, txtConsultaCpf2.getText());

    }//GEN-LAST:event_bAtualizarCliente2ActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed

        DAO dao = new DAO();

        for(CadastroCliente c : dao.readBuscaCliente(txtConsultaCpf2.getText())){

            txtBuscaNome2.setText(c.getNomeCompleto());
            txtBuscaNasc2.setText(c.getDataNascimento());
            txtBuscaTelefone.setText(c.getTelefone());
            txtBuscaSexo.setText(c.getSexo());
            txtBuscaCep.setText(c.getCep());
            txtBuscaEndereco.setText(c.getEndereco());
            txtBuscaCidade.setText(c.getCidade());
            txtBuscaEstado.setText(c.getEstado());
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bLimparBusca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparBusca2ActionPerformed
        txtConsultaCpf2.setText("");
        txtBuscaNome2.setText("");
        txtBuscaNasc2.setText("");
        txtBuscaTelefone.setText("");
        txtBuscaSexo.setText("");
        txtBuscaCep.setText("");
        txtBuscaEndereco.setText("");
        txtBuscaCidade.setText("");
        txtBuscaEstado.setText("");
    }//GEN-LAST:event_bLimparBusca2ActionPerformed

    private void bLimparConsultar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparConsultar7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLimparConsultar7ActionPerformed

    private void bBuscar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscar8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bBuscar8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidoVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidoVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidoVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidoVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BuscaCliente2;
    private javax.swing.JPanel CarrinhoDeCompras;
    private javax.swing.JPanel ConsultaProdutos2;
    private javax.swing.JButton bAtualizarCliente2;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bBuscar1;
    private javax.swing.JButton bBuscar2;
    private javax.swing.JButton bBuscar3;
    private javax.swing.JButton bBuscar4;
    private javax.swing.JButton bBuscar5;
    private javax.swing.JButton bBuscar6;
    private javax.swing.JButton bBuscar8;
    private javax.swing.JButton bDeletarCliente2;
    private javax.swing.JButton bLimparBusca2;
    private javax.swing.JButton bLimparConsultar;
    private javax.swing.JButton bLimparConsultar1;
    private javax.swing.JButton bLimparConsultar2;
    private javax.swing.JButton bLimparConsultar3;
    private javax.swing.JButton bLimparConsultar4;
    private javax.swing.JButton bLimparConsultar5;
    private javax.swing.JButton bLimparConsultar7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTProdutos;
    private javax.swing.JTable jTProdutos1;
    private javax.swing.JTable jTProdutos2;
    private javax.swing.JTable jTProdutos3;
    private javax.swing.JTable jTProdutos4;
    private javax.swing.JTable jTProdutos5;
    private javax.swing.JTable jTProdutos7;
    private javax.swing.JTable jTProdutos8;
    private javax.swing.JPanel totalVenda;
    private javax.swing.JLabel txTotalVenda;
    private javax.swing.JTextField txtBuscaNasc2;
    private javax.swing.JTextField txtBuscaNome2;
    private javax.swing.JFormattedTextField txtConsultaCpf2;
    private javax.swing.JTextField txtConsultaProduto;
    private javax.swing.JTextField txtConsultaProduto1;
    private javax.swing.JTextField txtConsultaProduto2;
    private javax.swing.JTextField txtConsultaProduto3;
    private javax.swing.JTextField txtConsultaProduto4;
    private javax.swing.JTextField txtConsultaProduto5;
    private javax.swing.JTextField txtConsultaProduto7;
    // End of variables declaration//GEN-END:variables
}
