/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Conexao.DAO;
import Objetos.Usuario;

/**
 *
 * @author phdam
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form UserT
     */
    public User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        jPanel34 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        txtConsultaCpfU13 = new javax.swing.JFormattedTextField();
        jPanel32 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        txtNomeBuscaU13 = new javax.swing.JTextField();
        bDeletarU13 = new javax.swing.JButton();
        bAtualizarU13 = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        txtBuscaNascU13 = new javax.swing.JTextField();
        bBuscarU = new javax.swing.JButton();
        bLimparU = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Usuários"));
        jPanel33.setLayout(null);

        jLabel14.setText("Nome");
        jPanel33.add(jLabel14);
        jLabel14.setBounds(11, 24, 31, 16);

        txtNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeUsuarioActionPerformed(evt);
            }
        });
        jPanel33.add(txtNomeUsuario);
        txtNomeUsuario.setBounds(11, 46, 314, 24);

        jPanel34.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setForeground(new java.awt.Color(153, 255, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/mole.png"))); // NOI18N
        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(153, 255, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/limpar-limpo.png"))); // NOI18N
        jButton1.setText("  Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel33.add(jPanel34);
        jPanel34.setBounds(11, 182, 314, 54);

        jLabel1.setText("Digite uma senha:");
        jPanel33.add(jLabel1);
        jLabel1.setBounds(11, 76, 94, 16);

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        jPanel33.add(txtSenha);
        txtSenha.setBounds(11, 98, 314, 24);

        jPanel1.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 390, 310));

        jTabbedPane1.addTab("CADASTRAR", jPanel1);

        jPanel31.setBackground(new java.awt.Color(255, 255, 255));
        jPanel31.setBorder(javax.swing.BorderFactory.createTitledBorder("Busca de Usuários"));
        jPanel31.setForeground(new java.awt.Color(153, 255, 153));
        jPanel31.setLayout(null);

        jLabel62.setText("CPF");
        jPanel31.add(jLabel62);
        jLabel62.setBounds(18, 35, 24, 16);

        try {
            txtConsultaCpfU13.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel31.add(txtConsultaCpfU13);
        txtConsultaCpfU13.setBounds(45, 32, 135, 23);

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel63.setText("Nome");

        txtNomeBuscaU13.setOpaque(false);

        bDeletarU13.setBackground(new java.awt.Color(102, 102, 102));
        bDeletarU13.setForeground(new java.awt.Color(153, 255, 153));
        bDeletarU13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete.png"))); // NOI18N
        bDeletarU13.setText("Deletar");
        bDeletarU13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeletarU13ActionPerformed(evt);
            }
        });

        bAtualizarU13.setBackground(new java.awt.Color(102, 102, 102));
        bAtualizarU13.setForeground(new java.awt.Color(153, 255, 153));
        bAtualizarU13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/updated.png"))); // NOI18N
        bAtualizarU13.setText("Atualizar");
        bAtualizarU13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtualizarU13ActionPerformed(evt);
            }
        });

        jLabel64.setText("Senha");

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeBuscaU13)
                    .addComponent(txtBuscaNascU13)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                        .addComponent(bAtualizarU13, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(bDeletarU13, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel64)
                            .addComponent(jLabel63))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel63)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeBuscaU13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel64)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscaNascU13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDeletarU13, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(bAtualizarU13, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addGap(335, 335, 335))
        );

        jPanel31.add(jPanel32);
        jPanel32.setBounds(18, 69, 361, 190);

        bBuscarU.setBackground(new java.awt.Color(102, 102, 102));
        bBuscarU.setForeground(new java.awt.Color(153, 255, 153));
        bBuscarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/binoculars.png"))); // NOI18N
        bBuscarU.setText("Buscar");
        bBuscarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarUActionPerformed(evt);
            }
        });
        jPanel31.add(bBuscarU);
        bBuscarU.setBounds(187, 31, 90, 24);

        bLimparU.setBackground(new java.awt.Color(102, 102, 102));
        bLimparU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/limpar-limpo.png"))); // NOI18N
        bLimparU.setText("Limpar");
        bLimparU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparUActionPerformed(evt);
            }
        });
        jPanel31.add(bLimparU);
        bLimparU.setBounds(285, 31, 98, 24);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("CONSULTAR", jPanel2);

        jMenu1.setText("Opção");

        jMenuItem1.setText("Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bDeletarU13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeletarU13ActionPerformed
        //deletarCliente(novoCliente);
    }//GEN-LAST:event_bDeletarU13ActionPerformed

    private void bAtualizarU13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtualizarU13ActionPerformed
        //atualizarCliente(novoCliente);
    }//GEN-LAST:event_bAtualizarU13ActionPerformed

    private void bBuscarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarUActionPerformed
        //buscarCliente(novoCliente);
    }//GEN-LAST:event_bBuscarUActionPerformed

    private void bLimparUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparUActionPerformed
        //limparCamposBusca();
    }//GEN-LAST:event_bLimparUActionPerformed

    private void txtNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeUsuarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Usuario u = new Usuario();
        DAO dao = new DAO();

        u.setNome(txtNomeUsuario.getText());
        u.setSenha(txtSenha.getText());
        dao.createUsuario(u);

        txtNomeUsuario.setText("");
        txtSenha.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //limparCamposCadastro();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtualizarU;
    private javax.swing.JButton bAtualizarU1;
    private javax.swing.JButton bAtualizarU10;
    private javax.swing.JButton bAtualizarU11;
    private javax.swing.JButton bAtualizarU12;
    private javax.swing.JButton bAtualizarU13;
    private javax.swing.JButton bAtualizarU2;
    private javax.swing.JButton bAtualizarU3;
    private javax.swing.JButton bAtualizarU4;
    private javax.swing.JButton bAtualizarU5;
    private javax.swing.JButton bAtualizarU6;
    private javax.swing.JButton bAtualizarU7;
    private javax.swing.JButton bAtualizarU8;
    private javax.swing.JButton bAtualizarU9;
    private javax.swing.JButton bBuscarU;
    private javax.swing.JButton bDeletarU;
    private javax.swing.JButton bDeletarU1;
    private javax.swing.JButton bDeletarU10;
    private javax.swing.JButton bDeletarU11;
    private javax.swing.JButton bDeletarU12;
    private javax.swing.JButton bDeletarU13;
    private javax.swing.JButton bDeletarU2;
    private javax.swing.JButton bDeletarU3;
    private javax.swing.JButton bDeletarU4;
    private javax.swing.JButton bDeletarU5;
    private javax.swing.JButton bDeletarU6;
    private javax.swing.JButton bDeletarU7;
    private javax.swing.JButton bDeletarU8;
    private javax.swing.JButton bDeletarU9;
    private javax.swing.JButton bLimparU;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtBuscaNascU;
    private javax.swing.JTextField txtBuscaNascU1;
    private javax.swing.JTextField txtBuscaNascU10;
    private javax.swing.JTextField txtBuscaNascU11;
    private javax.swing.JTextField txtBuscaNascU12;
    private javax.swing.JTextField txtBuscaNascU13;
    private javax.swing.JTextField txtBuscaNascU2;
    private javax.swing.JTextField txtBuscaNascU3;
    private javax.swing.JTextField txtBuscaNascU4;
    private javax.swing.JTextField txtBuscaNascU5;
    private javax.swing.JTextField txtBuscaNascU6;
    private javax.swing.JTextField txtBuscaNascU7;
    private javax.swing.JTextField txtBuscaNascU8;
    private javax.swing.JTextField txtBuscaNascU9;
    private javax.swing.JFormattedTextField txtConsultaCpfU;
    private javax.swing.JFormattedTextField txtConsultaCpfU1;
    private javax.swing.JFormattedTextField txtConsultaCpfU10;
    private javax.swing.JFormattedTextField txtConsultaCpfU11;
    private javax.swing.JFormattedTextField txtConsultaCpfU12;
    private javax.swing.JFormattedTextField txtConsultaCpfU13;
    private javax.swing.JFormattedTextField txtConsultaCpfU2;
    private javax.swing.JFormattedTextField txtConsultaCpfU3;
    private javax.swing.JFormattedTextField txtConsultaCpfU4;
    private javax.swing.JFormattedTextField txtConsultaCpfU5;
    private javax.swing.JFormattedTextField txtConsultaCpfU6;
    private javax.swing.JFormattedTextField txtConsultaCpfU7;
    private javax.swing.JFormattedTextField txtConsultaCpfU8;
    private javax.swing.JFormattedTextField txtConsultaCpfU9;
    private javax.swing.JTextField txtNomeBuscaU;
    private javax.swing.JTextField txtNomeBuscaU1;
    private javax.swing.JTextField txtNomeBuscaU10;
    private javax.swing.JTextField txtNomeBuscaU11;
    private javax.swing.JTextField txtNomeBuscaU12;
    private javax.swing.JTextField txtNomeBuscaU13;
    private javax.swing.JTextField txtNomeBuscaU2;
    private javax.swing.JTextField txtNomeBuscaU3;
    private javax.swing.JTextField txtNomeBuscaU4;
    private javax.swing.JTextField txtNomeBuscaU5;
    private javax.swing.JTextField txtNomeBuscaU6;
    private javax.swing.JTextField txtNomeBuscaU7;
    private javax.swing.JTextField txtNomeBuscaU8;
    private javax.swing.JTextField txtNomeBuscaU9;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
